a = input('Digite Algo: ')
print('Obrigado:', type(a))
print('So tem espaço',a.isspace())
print('E um numero',a.isnumeric())
print('E Alfanumerico:',a.isalpha())
print('E Alafanumerico: ',a.isalnum())
print('Esta em Maiusculo:',a.isupper())
print('Esta em Minuscula :',a.isupper())
print('Esta Capitalizada:',a.istitle())
print('E um Ptyhon: ',a.isdecimal())
